bjerkio/oidc-react

CHANGELOG.md
package.json

* Autosignin on expired user ([d5dce04](https://github.com/bjerkio/oidc-react/commit/d5dce04f51bdfcff49ab622f60875aedfe17fdb5))
* Fix withAuth export ([4e0e2e1](https://github.com/bjerkio/oidc-react/commit/4e0e2e11675eda83fc543779d53f51f2ff96284e))

chore(release): 1.0.0-alpha.5 [skip ci]

---

src/AuthContext.tsx
src/AuthContextInterface.ts
src/index.ts

Hello,
This PR adds support for the `client_secret` parameter, which is super important. This PR also re-exports some oidc-client types that oidc-react events use as parameters.

feat: Add client secret & re-export oidc-client types

---

.gitignore
src/AuthContext.tsx
src/AuthContextInterface.ts

The `UserManager` supports `automaticSilentRenew`. The `UserManager` created in oidc-react already has everything else necessary, so I figured I'd add this as a setting to this library instead of fully creating my own `UserManager` just for this setting.
At the moment, oidc-react doesn't do anything to alert or avoid an access token from expiring out from under the user. This is happening in the project I'm working on - users keep the browser tab open long enough that the access token is expiring, which results in them just getting unauthorized requests from our services.
The underlying oidc-client library has several ways to deal with this scenario, notably it has the `automaticSilentRenew` option which will attempt to renew the access token as its about to expire.
All that is missing …

feat: Add a pass-through option for UserManager's automaticSilentRenew

---

src/index.ts

Pretty straight forward. oidc-client exports `Log` which can be used for debugging. I've included that now in the oidc-react exports.

fix: Including 'Log' in export

---

src/AuthContext.tsx
src/__tests__/AuthContext.test.tsx

Fixes https://github.com/bjerkio/oidc-react/issues/361
...I think. When I edited directly in node_modules (it complained when i npm linked because of duplicate react) it worked but this code is slightly different.

fix: Load new state from session/local storage when available after a silent renew

---

guides/WITHAUTH.md

The example snippet for HOC usage was importing the `useAuth` function rather than `withAuth` in the markdown documentation.

docs: fix incorrect import in HOC example

---

src/AuthContext.tsx

Update to the signincallback flow to make state returned from oidc-client available to the onSignIn event
fixes #447

fix: Remove `getUser` in callback handler

---

package.json
src/__tests__/AuthContext.test.tsx
yarn.lock

This upgrades the oidc-client package from 1.9.1 -> 1.11.5. It includes some good fixes, including a Firefox bug where silent renews were not working due to iframe's being `display: none` and then being ignored. I am not sure if the version was fixed at 1.9.1 for a specific reason, but I think it's a good and reasonably safe upgrade to do.
I also included a new test to chip away at https://github.com/bjerkio/oidc-react/issues/523.

feat: upgrade to oidc-client 1.11.5

---

package.json

similar to:
https://github.com/mui-org/material-ui/blob/bd79e8f8c5b8c77bc5c13d076377a18d2ceedfa2/packages/material-ui/package.json#L43
No need to force users to update react to version 17.0.x, its working fine for me with 16.8.x!

chore: Allow react 16.8.x

---

src/AuthContext.tsx
src/AuthContextInterface.ts

similar to other libraries:
```
const { ready } = useTranslation();
or
const { isLoading } = useAuth0(); 
```
I have chosen the name isLoading so it matches useAuth0.
This will help in the application code to proberly handling the gap until the session user is loaded (iff any). It can show a "loading " message.
Alternative 1: It might be more robust/future proof to setup a react reducer. This will help massively when we want to implement isAuthenticated, etc... Like auth0 is doing:
https://github.com/auth0/auth0-react/blob/master/src/reducer.tsx
-> Can be done later....
Alternative2: Instead of the two states (isLoading+userData) we could use one state with both of them inside.... In this "state object" we can also add isAuthenticated...

feat: `isLoading` state

---

src/AuthContext.tsx
src/AuthContextInterface.ts

userManager must be in a state as well
- Fixes react-hooks/exhaustive-deps warnings
- userManager can not be null -> fixes definition

refactor: Move `UserManager` to state

---

CHANGELOG.md
README.md
docs/interfaces/authcontextinterface.authcontextprops.md
docs/interfaces/authcontextinterface.authproviderprops.md
guides/QUICKSTART.md
package.json
src/AuthContext.tsx
src/AuthContextInterface.ts
src/__tests__/AuthContext.test.tsx
src/index.ts
yarn.lock

refactor!: replace oidc-client-js with oidc-client-ts

---

src/AuthContext.tsx

Store isMountedRef.current in useEffect hook since this could change while awaiting async operations.
This could also resolve the issue #814

fix: alway userData=null - isLoading=true

---

docs/interfaces/authcontextinterface.authproviderprops.md

This changed with version 2.0 of `oidc-client-ts` - this is now enabled by default.

docs: Corrected default for `automaticSilentRenew`

---

src/AuthContext.tsx
src/AuthContextInterface.ts

The package `oidc-client-ts` offers a way to pass extra query params to the authorization endpoint.
Documentation: [https://authts.github.io/oidc-client-ts/classes/OidcClientSettingsStore.html#extraQueryParams](url)

feat: add extraQueryParams to AuthProvider

---

src/AuthContext.tsx

Fixes: #922, and possibly some others. Influenced by authts/oidc-client-ts#402.
[TLDR](https://github.com/authts/oidc-client-ts/issues/402#issuecomment-1056999675):  
> The problem here is that the stored state is removed immediately after the redirection from login. So if the user presses "back", then logs again, there is no more state available, even tho the redirect URL contains a state parameter. In other words, oidc-client-ts tries to load the stored state, but none is available because it removed it the first time the user logged in.
Personally what I discovered was that upon redirect from login, we still had the auth params in our query string. So if one were to reload the page or browse forward a page then hit the back button, we'd encounter the same thing. [hasCodeInUrl() would …

fix: avoid reinitiating partial authentication flow when user is already authenticated 

---

src/AuthContext.tsx
src/AuthContextInterface.ts
src/__tests__/AuthContext.test.tsx

Fixes #965 
Fixes #966
Adds a callback handler to trigger a signoutRedirect in the event that token renewal fails. This can happen for instance if an active user puts their computer to sleep, and then returns long after the token has expired. `oidc-client-ts` attempts to renew the token and fails. This would cause the app to still appear to be logged in, but API requests that required authentication would fail.

fix: handle token refresh failure

---

src/AuthContext.tsx
src/__tests__/AuthContext.test.tsx

Fixes #981, may also fix #980 (although doubtful).

fix: isLoading has correct status when autoSignIn is disabled and user is signed out

---

CHANGELOG.md
package.json

This should retrigger the generation of a 3.0.4 release PR, so long as the 3.0.4 release/tag have been deleted in GitHub.

chore: reset 3.0.4 release

---

src/AuthContext.tsx
src/AuthContextInterface.ts

Useful  for providers missing proper CORS headers.
Continuation of <https://github.com/bjerkio/oidc-react/pull/715#issuecomment-1514691686>
Note:
I've tried running `generate-docs` but was unsuccessful:
```
yarn run v1.22.19
$ typedoc --gitRevision main --out docs src
[info] Loaded plugin typedoc-plugin-markdown
TypeDoc exiting with unexpected error:
TypeError: page.template is not a function
at MarkdownTheme.render (D:\dev\work\temp\oidc-react\node_modules\typedoc-plugin-markdown\dist\theme.js:39:49)
at Renderer.renderDocument (D:\dev\work\temp\oidc-react\node_modules\typedoc\dist\lib\output\renderer.js:183:40)
at D:\dev\work\temp\oidc-react\node_modules\typedoc\dist\lib\output\renderer.js:159:22
at Array.forEach (<anonymous>)
at Renderer.render …
```

Add `metadata` parameter to AuthContext

---

README.md
guides/HOOKS.md
guides/QUICKSTART.md
guides/WITHAUTH.md

This fixes documentation link to the examples repository. React examples language hint "tsx" improves formatting because the examples are not pure TypeScript.

docs: improve documentation

---

src/AuthContext.tsx

In current implementation with:
* React: 18.2.0 **strict mode**
* Identity Provider: IdentityServer4
* Flow: authorization code + pkce
We experience multiplied authorization code exchange requests as a result of not handling simulation of component immediate unmounting and remounting in strict mode.
`isMountedRef` cannot be used as it will be updated during next useEffect:

fix: multiplied code exchange requests in strict mode

---

package.json

There is a vulnerability with crypto-js which is used in the oidc-client-ts. Crypto-js version is bumped in oidc-client-ts, but it seems dependabot didn't catch it here. 
https://security.snyk.io/package/npm/crypto-js
This is the PR on oidc-client-ts:
https://github.com/authts/oidc-client-ts/pull/1221
CVE issue
https://www.cve.org/CVERecord?id=CVE-2023-46233

fix: CVE-2023-46233 fix

---

src/AuthContext.tsx
src/AuthContextInterface.ts

This new error callback let us have a better control (for giving feedback to the users) when the `signIn` function fails

feat: add `onSignInError` to AuthProvider

---

src/__tests__/auth-context.test.tsx
src/auth-context.tsx

Fixes issue #1074 so that onSignIn is called when signin in with hash params. Adds test to ensure callback works with hash routing.

fix: Call onSignIn when using hash params

---

package.json
pnpm-lock.yaml
src/__tests__/auth-context.test.tsx
src/auth-context-interface.ts
src/auth-context.tsx

The wrapper `signInPopup()` calls `userManager.signinCallback()` on the main app window, right after popup promise is resolved. This is not correct, as `signinCallback()` should be only invoked on the redirect callback page or route. 
In popup flow after code is exchanged for token the popup window dispatches `postMessage()` to the opener in `oidc-client-ts` and is closed. However, when `signinCallback()` as is currently the popup window gets closed when token is retrieved and main window tries to perform OIDC callback, which fails and tries to send `postMessage()` to the `window.opener` which doesn't exist. This causes error `No window.opener.` from `oidc-client-ts` to be thrown.
This changes fixes the flow and additionally adds wrapper around `userManager.signinCallback()` to the …

feat!: fix handling popup sign in, add wrapper function for callback
